services:
  api:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "7000:7000"
    volumes:                       # 開発時ホットリロード
      - ./backend:/code
      - ~/.aws:/root/.aws:ro            # SSO プロファイル (dev-gaia) を読み込む
    environment:                        # プロファイルが確実に見えるように明示
      AWS_CONFIG_FILE: /root/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /root/.aws/credentials
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload
    restart: unless-stopped

  web:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:7000
    ports:
      - "3000:3000"
    # ⚠️ volumes は付けず、イメージ内の .next を保持
    depends_on:
      - api
    restart: unless-stopped
