version: "3.8"

services:
  api:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "7000:7000"
    restart: unless-stopped

  web:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:7000
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
