name: CI
on:
  push:
    branches: [main]
  pull_request: {}
  # 手動で走らせたい場合は ↓ を追加
  # workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # ① Secrets を backend/.env.docker に書き込む
      - name: Prepare env file for Docker
        run: |
          mkdir -p backend
          cat > backend/.env.docker <<EOF
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
# AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
# AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
EOF
          echo "✅ .env.docker written"

      # ② backend イメージをビルド
      - name: Build backend image
        run: docker compose build api

      # ③ pytest を実行（‐e でキーを直渡し）
      - name: Run tests
        run: |
          docker compose run --rm \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            api pytest -q
