name: CI
on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      # Python だけでなく Docker ビルド用の環境も使うので Buildx は残す
      - uses: docker/setup-buildx-action@v3

      # ① Secrets を書き込んだ .env.docker を生成
      - name: Prepare env file for Docker
        run: |
          mkdir -p backend
          cat <<EOF > backend/.env.docker
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          # ↓将来 Bedrock を使うならここに追加
          # AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          ls -l backend/.env.docker   # デバッグ用に内容は伏せたまま存在確認

      # ② backend イメージをビルド（キャッシュ効くならお好みで arg 維持）
      - name: Build backend image
        run: docker compose build api

      # ③ pytest を実行（env_file 経由なので -e は不要）
      - name: Run tests
        run: docker compose run --rm api pytest -q
