name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # ← 追加

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create dummy env file
        run: |
          mkdir -p backend
          touch backend/.env.docker

      - name: Build backend image (api)
        run: docker compose build --build-arg BUILDKIT_INLINE_CACHE=1 api

      - name: Run tests
        run: docker compose run --rm -e OPENAI_API_KEY=$OPENAI_API_KEY api pytest -q
