name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create dummy env file
        run: |
          mkdir -p backend
          touch backend/.env.docker

      # --- ① backend イメージをビルド ---------------------------------
      - name: Build backend image (api)
        run: docker compose build --build-arg BUILDKIT_INLINE_CACHE=1 api

      # --- ② pytest を実行 -------------------------------------------
      - name: Run tests
        # --rm で終了後にコンテナ削除
        run: docker compose run --rm api pytest -q
